
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 8;
  public static final int DECIMAL = 10;
  public static final int COMA = 6;
  public static final int RTRUE = 11;
  public static final int RNULL = 13;
  public static final int ENTERO = 9;
  public static final int EOF = 0;
  public static final int CORCH_CIERRA = 5;
  public static final int error = 1;
  public static final int RFALSE = 12;
  public static final int DOS_PUNTOS = 7;
  public static final int LLAVE_ABRE = 2;
  public static final int CORCH_ABRE = 4;
  public static final int LLAVE_CIERRA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "CORCH_ABRE",
  "CORCH_CIERRA",
  "COMA",
  "DOS_PUNTOS",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "RTRUE",
  "RFALSE",
  "RNULL"
  };
}

